### ISSUE TITLE
theme_bakeoff()

### ISSUE THREAD

**Issue by JeremyNguyenPhD** [apreshill/talks#2]
Is there any chance you'd be able to share `theme_bakeoff()`? Your plots just look so good, and I'm trying to make mine own plots look better.

**Comment by apreshill** [comment]
Sure! Not on CRAN yet, but I reworked the package and make the color palettes here: https://bakeoff.netlify.app/reference/index.html#section-scales

**Comment by JeremyNguyenPhD** [comment]
Thank you!
